First test branch
wacoo/Hello-Microverse pull request #4
Opened 2023-05-30 13:00 UTC by wacoo

- Added index.html file
- Added style.css file
- Added .gitignore file
- Added test.md file
- Added node_modules to .gitignore file
- Added test.md to .gitignore file

2023-05-30 13:18 UTC, BregornOriginal requested changes
Hi @wacoo  

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

***Remember when you write your commits they have to be meaningful, so instead of writing `added` it would be better to create a commit like `add...` or `create...` Kinldy do this in your next commits***

![giphy (5)](https://github.com/wacoo/Hello-Microverse/assets/93630700/0dac92e8-c977-4d2a-a557-cb15b9478f40)

## Highlights

✅ Linters are passing
✅ Excellent Pull Request naming and description 💯 
✅ Excellent commit history
✅ Correct use of GitHub Flow
✅ Good work adding files to your `.gitignore` file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 13:18 UTC, BregornOriginal commented on README.md
> +# Hello Microverse
Good work creating your Readme file with some information about your project

As your Readme file is like an introduction to your repository, it's a requirement to attach all the information possible about it. To make it easier, there's a template provided by Microverse. [This template](https://github.com/microverseinc/readme-template)

- Kindly update your README file with this template and your information, remember to only add to your README file the information that you are adding in your repository

2023-05-30 15:02 UTC, wacoo commented on README.md
> +# Hello Microverse
Thank you for the comments. Do I need to add every heading in the readme template? The project doesn't use a database, live demo, or install and deployment procedure.

2023-05-30 15:04 UTC, wacoo commented on README.md
> +# Hello Microverse
What should I fix in my repo readme?

2023-05-30 15:51 UTC, Strangeal requested changes
Hi @wacoo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Alt Text](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 15:51 UTC, Strangeal commented on README.md
> +# Hello Microverse
- [ ] As suggested by the previous reviewer, kindly consider documenting your project properly using the `README` template provided in the project requirement [here](https://github.com/microverseinc/readme-template)

2023-05-31 12:26 UTC, shahadat3669 requested changes
Hi @wacoo,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![170491251-b1add8ba-b18f-4648-a893-20e510d957fd](https://github.com/wacoo/Hello-Microverse/assets/55840999/3c0d7d31-3c5b-43a5-be4f-c1125ecb82e9)

## Highlights
✅ Linters are passing
✅ Excellent Pull Request naming and description 💯
✅ Excellent commit history
✅ Correct use of GitHub Flow
✅ Good work adding files to your .gitignore file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- You've done a great job adding the linter configuration for code checking using GitHub workflow. However, it's worth noting that you can also check your code locally using linter packages. All you need to do is install the necessary linter packages and run specific commands in your terminal. You can check the [linter configuration repo](https://github.com/microverseinc/linters-config/tree/master/html-css#set-up-linters-in-your-local-env) to learn how to do so.
![image](https://github.com/wacoo/Hello-Microverse/assets/55840999/1f5a5989-9a83-40db-99d1-618ca8f822c7)

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 12:26 UTC, shahadat3669 commented on README.md
> +> Add a link to your deployed project.
Great work on the Readme file! However, if you have decided not to deploy the application now, remove this section, or you can deploy it and add the deployed link in this section. If you're unsure about how to deploy the application, don't worry, you will learn it in a future project. In the meantime, feel free to delete this section and ensure that the 'live demo' is also removed from the **Table of Contents**.

Please remove the live demo section if the application won't be deployed.
![image](https://github.com/wacoo/Hello-Microverse/assets/55840999/84580445-f6ed-431a-9f17-775311b7d719)
![image](https://github.com/wacoo/Hello-Microverse/assets/55840999/89b904e1-2988-4aba-bea3-aba01ad7eef6)

2023-05-31 12:26 UTC, shahadat3669 commented on README.md
> +> 3. Type git clone [link-to-the-repo]
Great job on adding instructions for using your repository!:+1: However, I recommend removing the placeholder text from the Readme template and replacing it with documentation that is specific and relevant to the current project. This will greatly benefit users by providing them with clear and useful information. For example, consider including the following instructions to guide users on cloning the repository and setting it up:

- Use the cd command to navigate to your desired folder:
```
cd C:\Users\...
```
- Clone this repository to your desired folder by running the following command in your terminal:
```
git clone https://github.com/wacoo/Hello-Microverse
```
- Change to the cloned repository's directory:
```
cd Hello-Microverse
```

2023-05-31 12:26 UTC, shahadat3669 commented on README.md
> +
Well done on adding the 'Future Features' section!:+1: However, it would be helpful to include 1-3 potential features in this section. It will demonstrate your vision and give readers an idea of what to expect. Keep up the good work!

Please include 1-3 potential fractures in this section.

Example feature:
- I will deploy this project.

2023-05-31 12:26 UTC, shahadat3669 commented on README.md
> +- None
Wonderful job on adding the license section! To complete it, I suggest replacing the placeholder text with the actual license file in your repository. 

To add a license file, in the readme template repository, you can find a file named '**MIT**' which corresponds to the MIT license. Please add that file to your repository _(remember to delete placeholders)_ and update the section with a link to the license file. This will ensure that users have access to the license terms and understand the permissions and restrictions associated with your project. Keep up the great work!:point_down:

![image](https://github.com/wacoo/Hello-Microverse/assets/55840999/720077f3-502c-4a0a-a480-1c74c1e0b42b)

2023-05-31 12:26 UTC, shahadat3669 commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Great work on the Readme file! :grinning: However, if you have decided not to add any FAQ questions at the moment, it would be best to remove the FAQ section. Alternatively, if you have some frequently asked questions in mind, you can add them to provide additional information to users.

Please delete this section and ensure that the 'FAQ' entry is also removed from the Table of Contents. By keeping the Readme focused and concise, users will be able to easily navigate and find the information they need. Keep up the good work.

Example FAQ::point_down:
- Q1: Can I use your Repo for personal use?
Ans: Yes, you can. Please check out the license section.

2023-05-31 12:26 UTC, shahadat3669 commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
Great job on having functional links to your GitHub and Twitter accounts!:+1: However, it seems that you forgot to include a link to your LinkedIn profile.

Please add your LinkedIn link to ensure that users have a complete set of contact information and can connect with you professionally.

2023-05-31 12:26 UTC, shahadat3669 commented on README.md
> +> Describe between 1-3 key features of the application.
I noticed that there are still some instances where placeholder text from the Readme template is present, such as
> Describe between 1-3 key features of the application.

 To enhance the clarity and readability of the document, I recommend removing these placeholder texts. By doing so, the Readme will be more concise and focused, allowing users to easily navigate and find the relevant information they need. 

Great job on your progress so far, and keep up the good work

2023-05-31 12:26 UTC, shahadat3669 commented on README.md
> +</details>
I understand that in this project, you are not utilizing a **server** or **database**. However, since they are not relevant to the current project, I recommend removing any mentions or references to them. Focusing on the specific technologies and components used in the current project will ensure that the Readme remains concise and aligned with the project's scope. 

Excellent work so far, and keep up the good work!😄

2023-05-31 15:05 UTC, vickymarz approved these changes
Hi @wacoo, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Requested changes implemented ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 15:20 UTC, merged